on:
  workflow_dispatch:
jobs:
  job1:
  #this pipeline strategies allow pipeline to continuou even this job failed
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [14.x, 15.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
    # action to install nodejs on the runner
      - uses: actions/setup-node@v3.6.0
        with:
          node_version: ${{ matrix.node_version }}