on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      # use action found in the marketplace
        uses: actions/checkout@v5.0.0


      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
    # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}
    # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASS }}
 
          
        
      - name: build front-end docker image
        working-directory: front-end
        run: |
          docker build -t maro4299311/inspirehub-jenkins-dynamic-agent:${{ github.run_number }} .
          docker push maro4299311/inspirehub-jenkins-dynamic-agent:${{ github.run_number }}    

    #   - name: Notify Microsoft Teams on Success
    #     uses: Skitionek/notify-microsoft-teams@v1.0.4
    #     if: success()
    #     with:
    # # teams incoming webhook url
    #       webhook_url: ${{ secrets.MS_TEAMS }}
    # # JSON object to send to Microsoft Teams
    #       raw: |
    #          {
    #           "@type": "MessageCard",
    #           "@context": "https://schema.org/extensions",
    #           "summary": "Pipeline Status",
    #           "themeColor": "00FF00",
    #           "title": "✅ Pipeline Successful!",
    #           "text": "Frontend image build and push completed successfully for run #${{ github.run_number }} on branch `${{ github.ref_name }}`."
    #           }
        
      - name: Notify Microsoft Teams on Failure
        uses: Skitionek/notify-microsoft-teams@v1.0.4
        if: failure()
        with:
          webhook_url: ${{ secrets.MS_TEAMS }}
          raw: |
            {
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "summary": "Pipeline Status",
              "themeColor": "FF0000",
              "title": "❌ Pipeline Failed!",
              "text": "Frontend build and push failed for run #${{ github.run_number }} on branch `${{ github.ref_name }}`."
            }

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      # use action found in the marketplace
        uses: actions/checkout@v5.0.0


      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
    # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}
    # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASS }}
 
          
        
      - name: build backend docker image
        working-directory: backend
        run: |
          docker build -t maro4299311/nodejs:${{ github.run_number }} .
          docker push maro4299311/nodejs:${{ github.run_number }}
      
    #   - name: Notify Microsoft Teams on Success
    #     uses: Skitionek/notify-microsoft-teams@v1.0.4
    #     if: success()
    #     with:
    # # teams incoming webhook url
    #       webhook_url: ${{ secrets.MS_TEAMS }}
    # # JSON object to send to Microsoft Teams
    #       raw: |
    #          {
    #           "@type": "MessageCard",
    #           "@context": "https://schema.org/extensions",
    #           "summary": "Pipeline Status",
    #           "themeColor": "00FF00",
    #           "title": "✅ Pipeline Successful!",
    #           "text": "backend image build and push completed successfully for run #${{ github.run_number }} on branch `${{ github.ref_name }}`."
    #           }
        
      - name: Notify Microsoft Teams on Failure
        uses: Skitionek/notify-microsoft-teams@v1.0.4
        if: failure()
        with:
          webhook_url: ${{ secrets.MS_TEAMS }}
          raw: |
            {
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "summary": "Pipeline Status",
              "themeColor": "FF0000",
              "title": "❌ Pipeline Failed!",
              "text": "backend build and push failed for run #${{ github.run_number }} on branch `${{ github.ref_name }}`."
            }

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  post-action:
    runs-on: ubuntu-latest
    needs: [ build-frontend, build-backend ]
    steps:
      - name: Notify Microsoft Teams on Pipeline Success
        uses: Skitionek/notify-microsoft-teams@v1.0.4
        if: success()
        with:
    # teams incoming webhook url
          webhook_url: ${{ secrets.MS_TEAMS }}
    # JSON object to send to Microsoft Teams
          raw: |
             {
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "summary": "Pipeline Status",
              "themeColor": "00FF00",
              "title": "✅ Pipeline Successful!",
              "text": "frontend and backend images are built and pushed  successfully for run #${{ github.run_number }} on branch `${{ github.ref_name }}`."
              }



