on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      # use action found in the marketplace
        uses: actions/checkout@v5.0.0


      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
    # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}
    # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASS }}
 
          
        
      - name: build front-end docker image
        working-directory: front-end
        run: |
          docker build -t maro4299311/inspirehub-jenkins-dynamic-agent:${{ github.run_number }} .
          docker push maro4299311/inspirehub-jenkins-dynamic-agent:${{ github.run_number }}