on:
  push:
    branches:
      - "**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      # use action found in the marketplace
        uses: actions/checkout@v5.0.0
      
      - name: run test
        working-directory: src
        run: npm test